apiVersion: apps/v1
kind: Deployment
metadata:
  name: ts-example-site
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ts-example-site
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: ts-example-site
    spec:
      imagePullSecrets:
        - name: cred-dockerhub
      nodeSelector:
        workload: pro
      tolerations:
        - key: dr
          operator: Exists
          effect: NoSchedule
        - key: node.kubernetes.io/unreachable
          operator: Exists
          effect: NoExecute
        - key: node.kubernetes.io/not-ready
          operator: Exists
          effect: NoExecute
        - key: dedicated
          operator: Equal
          value: pro
          effect: NoSchedule
      containers:
        - name: site
          image: virgiliofilhos/site-typescript-nodejs:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          env:
            - name: PORT
              value: "8080"
          startupProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 2
            periodSeconds: 3
            timeoutSeconds: 2
            successThreshold: 1
            failureThreshold: 40
          readinessProbe:
            httpGet:
              path: /readyz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 2
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 20
            periodSeconds: 20
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 3
